version: '3'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  zipline:
    image: ghcr.io/diced/zipline
    ports:
      - '127.0.0.1:3000:3000'
    restart: unless-stopped
    environment:
      - CORE_RETURN_HTTPS=true
      - CORE_SECRET=$CORE_SECRET
      - CORE_HOST=0.0.0.0
      - CORE_PORT=3000
      - CORE_DATABASE_URL=$CORE_DATABASE_URL
      - CORE_LOGGER=true
      - UPLOADER_ROUTE=/
      - UPLOADER_USER_LIMIT=200mb
      - UPLOADER_DEFAULT_EXPIRATION=90d
      - UPLOADER_DISABLED_EXTENSIONS=exe,scr,cpl,doc,jar
      - CHUNKS_ENABLED=true
      - CHUNKS_CHUNKS_SIZE=25mb
      - CHUNKS_MAX_SIZE=95mb
      # FEATURES_INVITES=true
      - FEATURES_USER_REGISTRATION=true
      # FEATURES_DEFAULT_AVATAR=./public/weeb.jpg
      - FEATURES_ROBOTS_TXT=true
      - WEBSITE_TITLE=Awoo Corner
      - WEBSITE_SHOW_FILES_PER_USER=false
      - WEBSITE_SHOW_VERSION=false
      - WEBSITE_EXTERNAL_LINKS=[{"label":"How to Use","link":"https://rentry.org/"}]
      - EXIF_REMOVE_GPS=true
    volumes:
      - './uploads:/zipline/uploads'
      - './public:/zipline/public'
    depends_on:
      - 'postgres'

volumes:
  pg_data: