services:
  redlib:
    image: ghcr.io/cycneuramus/containers:redlib
    container_name: redlib
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    labels:
      - 'wud.watch=true'
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
    env_file:
      - ./envs/redlib.env
    ports:
      - '127.0.0.1:6672:8080'
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8080/settings"]
      interval: 5m
      timeout: 3s
    restart: unless-stopped