version: "3.3"
services:
  icloudpd:
    stdin_open: true
    tty: true
    container_name: icloudpd
    volumes:
      - ${PHOTO}:/data
    environment:
      - TZ=Etc/UTC
    image: icloudpd/icloudpd:latest
    restart: unless-stopped
    command: icloudpd --directory /data --username ${EMAIL} --password ${PASS}
      --watch-with-interval 43200