version: "3.3"
services:
    watchtower:
        container_name: watchtower
        image: containrrr/watchtower
        restart: always
        environment:
            - watchtower
            - WATCHTOWER_CLEANUP
            - WATCHTOWER_NOTIFICATIONS=shoutrrr
            - WATCHTOWER_NOTIFICATION_URL=$NTFY
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
