services:
  justlog:
    image: ghcr.io/gempir/justlog
    container_name: justlog
    hostname: justlog
    restart: unless-stopped
    ports:
      - "8025:8025"
    volumes:
      - ${USERDIR}/apps/${APP}/config.json:/etc/justlog.json
      - ${USERDIR}/apps/${APP}/logs:/logs
    labels:
      - "com.centurylinklabs.watchtower.enable=false"