version: "3"
services:
  searxng-search:
    image: searxng/searxng
    container_name: searxng-search
    hostname: searxng
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
    - "8088:8080"
    networks:
      - frontend
    environment:
      - BASE_URL=http://localhost:$PORT
      - INSTANCE_NAME=searXNG
    volumes:
      - ${USERDIR}/apps/${CONTAINER}:/etc/searxng
networks:
  frontend:
    external: true
