services:

  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    restart: unless-stopped
    networks:
      - frontend
    environment:
      - GID=1000
      - COLLECTIONS=crowdsecurity/linux crowdsecurity/caddy crowdsecurity/appsec-generic-rules crowdsecurity/appsec-virtual-patching crowdsecurity/http-cve crowdsecurity/whitelist-good-actors
      - BOUNCER_KEY_CADDY=${CROWDSEC_API_KEY}
    volumes:
      - ./app_data/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./app_data/crowdsec:/etc/crowdsec
      - ./app_data/crowdsec/db:/var/lib/crowdsec/data
      - ./app_data/logs:/var/log/caddy:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    security_opt:
      - no-new-privileges=true

  caddy:
    build: ./dockerfile-caddy
    container_name: caddy
    restart: unless-stopped
    networks:
      - frontend
    environment:
      - DOMAIN
      - CLOUDFLARE_API_TOKEN
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./app_data/Caddyfile:/etc/caddy/Caddyfile
      - ./app_data/conf:/etc/caddy/conf
      - ./app_data/config:/config
      - ./app_data/data:/data
      - ./app_data/logs:/var/log/caddy
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    security_opt:
      - no-new-privileges=true
      
networks:
  frontend:
    external: true