version: "3"

services:
  ownfoil:
    container_name: ownfoil
    image: a1ex4/ownfoil
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${USERDIR}/apps/${CONTAINER}/games:/games
    ports:
      - "8465:8465"