services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "node src/scripts/health-check.js"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - frontend
    volumes:
      - ${USERDIR}/apps/${CONTAINER}/app_data/actual-data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.actual.entrypoints=http
      - traefik.http.routers.actual.rule=Host(`actual.local.example.com`)
      - traefik.http.middlewares.actual-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.actual.middlewares=actual-https-redirect
      - traefik.http.routers.actual-secure.entrypoints=https
      - traefik.http.routers.actual-secure.rule=Host(`actual.local.example.com`)
      - traefik.http.routers.actual-secure.tls=true
      - traefik.http.routers.actual-secure.service=actual
      - traefik.http.services.actual.loadbalancer.server.port=5006
      - traefik.docker.network=frontend
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 250M
        reservations:
          cpus: '0.50'
          memory: 50M

networks:
  frontend:
    external: true