version: "3"

services:

  # --- MariaDB
  db:
    image: mariadb:10.7
    container_name: linkace-db
    networks:
      - backend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db:/var/lib/mysql

  # --- LinkAce Image with PHP 7.4 and nginx
  app:
    image: linkace/linkace:simple
    container_name: linkace
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - db
    networks:
      - frontend
      - backend
    volumes:
      - ${USERDIR}/apps/${CONTAINER}/.env:/app/.env
      - ${USERDIR}/apps/${CONTAINER}/backups:/app/storage/app/backups
      - linkace_logs:/app/storage/logs
    labels:
      - traefik.enable=true
      - traefik.http.routers.linkace.entrypoints=http
      - traefik.http.routers.linkace.rule=Host(`linkace.local.example.com`)
      - traefik.http.middlewares.linkace-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.linkace.middlewares=linkace-https-redirect
      - traefik.http.routers.linkace-secure.entrypoints=https
      - traefik.http.routers.linkace-secure.rule=Host(`linkace.local.example.com`)
      - traefik.http.routers.linkace-secure.tls=true
      - traefik.http.routers.linkace-secure.service=linkace
      - traefik.http.services.linkace.loadbalancer.server.port=80
      - traefik.docker.network=frontend
volumes:
  linkace_logs:
  db:
    driver: local

networks:
  frontend:
    external: true
  backend:
    external: true
