version: "3.5"
services:
  postgres:
    image: postgres:16-alpine
    container_name: linkwarden-db
    env_file: .env
    restart: always
    networks:
      - backend
    volumes:
      - ${USERDIR}/apps/${CONTAINER}/app_data/db:/var/lib/postgresql/data

  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    container_name: linkwarden
    networks:
      - frontend
      - backend
    volumes:
      - ${USERDIR}/apps/${CONTAINER}/app_data/data:/data/data
    depends_on:
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.linkwarden.entrypoints=http
      - traefik.http.routers.linkwarden.rule=Host(`linkwarden.local.example.com`)
      - traefik.http.middlewares.linkwarden-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.linkwarden.middlewares=linkwarden-https-redirect
      - traefik.http.routers.linkwarden-secure.entrypoints=https
      - traefik.http.routers.linkwarden-secure.rule=Host(`linkwarden.local.example.com`)
      - traefik.http.routers.linkwarden-secure.tls=true
      - traefik.http.routers.linkwarden-secure.service=linkwarden
      - traefik.http.services.linkwarden.loadbalancer.server.port=3000
      - traefik.docker.network=frontend

networks:
  frontend:
    external: true
  backend:
    external: true
