version: "3.8"

services:
   icloudpd2:
      hostname: icloudpd2
      container_name: icloudpd2
      environment:
         - TZ=Etc/UTC
      image: boredazfcuk/icloudpd
      healthcheck:
         test: /usr/local/bin/healthcheck.sh
         start_period: 30s
      restart: always
      volumes:
         - ./config/:/config
         - ./iCloud/:/home/user1/iCloud/