version: "3"

services:
  twitchdropminer:
    image: starkayc/twitch-drops-miner
    container_name: tdm-starkayc
    ports:
    - 5800:5800
    volumes:
      - ${USERDIR}/apps/${APP}/config:/TwitchDropsMiner/config
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=false