services:
  rustlog:
    image: ghcr.io/boring-nick/rustlog:master
    container_name: rustlog
    restart: unless-stopped
    depends_on:
      - clickhouse
    ports:
      - "8020:8020"
    volumes:
      - ${USERDIR}/apps/${CONTAINER}/config.json:/config.json
    labels:
      - com.centurylinklabs.watchtower.enable=false

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped
    env_file:
    - .env
    volumes:
      - ${USERDIR}/apps/${CONTAINER}/ch-data:/var/lib/clickhouse:rw
    labels:
      - com.centurylinklabs.watchtower.enable=false