services:
  asfclaim:
    image: ghcr.io/c4illin/asfclaim:master
    container_name: asfclaim
    restart: unless-stopped
    environment: # all are optional, defaults are listed below
      - ASF_PORT=1242
      - ASF_HOST=
      - ASF_PASSWORD=password
      - ASF_COMMAND_PREFIX=!
      - ASF_HTTPS=false
      - ASF_BOTS=asf