version: '3.4'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - ${USERDIR}/apps/${CONTAINER}/config:/config
            - ${USERDIR}/apps/${CONTAINER}/config/keys:/config/keys
        environment:
            - PUID=$PUID
            - PGID=$PGID
            - APP_KEY=$APP_KEY
            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE=
            - SPEEDTEST_SERVERS=
            - PRUNE_RESULTS_OLDER_THAN=0
            - CHART_DATETIME_FORMAT=
            - DATETIME_FORMAT=
            - APP_TIMEZONE=$TZ
            - DISPLAY_TIMEZONE=$TZ
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
