version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    network_mode: vpn
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
    volumes:
      - ${USERDIR}/apps/${CONTAINER}:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=$PIA_USER
      - OPENVPN_PASSWORD=$PIA_PASS
      - SERVER_REGIONS=US West
      - TZ=$TZ
      - UPDATER_PERIOD=24h
      - HTTPPROXY=on
      - DOT_PROVIDERS=quad9